### ISSUE TITLE
EJERCICIO 1 - PUNTO 1 Pedir el ingreso de dos números por terminal y mostrar la suma por la pantalla.

### ISSUE THREAD

**Issue by fvexe82** [EMTSTISPC/Grupo3#4]

**Comment by gonaiot** [comment]
@leolgonzalez 
Estimado, esta bien realizado el ejercicio. Aunque debiera ademas publicar su raw en pdf, de otra forma es incomodo visualizar su implementacion. Obligando a descargar hard y soft. 
Ud debe agilizar este mecanismo, proponiendo pruebas, por lo menos 5, y publicarlas. Tiene como ejemplo otros grupos que lo manejaron correctamente. saludos.
