### ISSUE TITLE
EJERCICIO 1 - PUNTO 2 Preguntar Nombre, Apellido, Dirección y Celular en mensajes diferentes. Completar las respuestas.

### ISSUE THREAD

**Issue by fvexe82** [EMTSTISPC/Grupo3#5]

**Comment by gonaiot** [comment]
@JDGA1997  
Estimado esta bien realizada su tarea, recuerde utilizar los comentarios. Esto le va a ayudar a realizar el mantenimiento del programa. Continué así.
