### ISSUE TITLE
EJERCICIO 1 - PUNTO 5 Ingresar una secuencia de 8 bits por terminal , que activaran los leds correspondientes por el puerto D.

### ISSUE THREAD

**Issue by fvexe82** [EMTSTISPC/Grupo3#8]

**Comment by gonaiot** [comment]
@maj3210  @fvexe82 
Estimados, el ejercicio no es el requerido. Esto me lleva a pensar que colocar los archivos .hex o .elf fue premeditado, porque pensaron que no se iban a revisar. Una pena. Porque muchos de uds trabajaron muy bien. 
En cuanto al scrum master que seria @fvexe82 es su responsabilidad chequear esto. Que paso? 
Ademas, de que podrian tranquilamente desarrollar otra tarea si tenia problemas para hacerla.

**Comment by fvexe82** [comment]
Profe buenas tardes, como SCRUM, tiene toda la razón, me faltó chequear el desarrollo final de la ISSUE, lo que si le aclaro, EN NINGUN MOMENTO FUE PREMEDITADO, se trató de aclarar entre todo el grupo las posibles dudas. Tal vez cometimos el error de no haber preguntado dudas que nos quedaron en el tintero, pero sirve para el aprendizaje y presentación de futuros proyectos, muchas gracias.
